// build.rs — runs once per crate compile. Produces:
//   - permissions/autogenerated/commands/<cmd>.toml  (allow-<cmd> + deny-<cmd>)
//   - permissions/autogenerated/reference.md
//   - the in-crate ACL manifest consumed by the Tauri runtime
//
// `tauri-plugin` is a *build-dependency*, not a runtime dep. In Cargo.toml:
//
//   [build-dependencies]
//   tauri-plugin = { version = "2", features = ["build"] }
//   schemars     = "0.8"   # only if you wire a scope schema
//
// And declare:
//
//   [package]
//   build = "build.rs"

// Pull scope.rs in via #[path] so both the crate AND this script see the same type.
// (Removing this also means removing .global_scope_schema(...) below.)
#[path = "src/scope.rs"]
mod scope;

/// Every snake_case command exposed via `#[tauri::command]` must appear here.
/// Renaming or removing entries is a breaking change for consumer capability files
/// (they reference `allow-<cmd>` / `deny-<cmd>`), so treat this list as semver-relevant.
const COMMANDS: &[&str] = &[
    "ping",
    "start_server",
    "stop_server",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        // Optional: ship a JSON Schema for the plugin-global scope so
        // capability authors get IDE autocomplete on `"scope": [ ... ]`.
        .global_scope_schema(schemars::schema_for!(scope::Entry))
        .build();

    // If your scope struct lives elsewhere, tell Cargo to invalidate the build
    // when it changes. `tauri_plugin::Builder` doesn't do this for you.
    println!("cargo:rerun-if-changed=src/scope.rs");
}
