// android/src/main/java/com/plugin/myplugin/MyPlugin.kt
//
// Generated by `tauri plugin android add` and then edited to add real commands.
// Tauri discovers this class via the @TauriPlugin annotation; @Command methods
// become reachable from Rust as run_mobile_plugin("methodName", payload).

package com.plugin.myplugin

import android.Manifest
import android.app.Activity
import android.webkit.WebView
import app.tauri.annotation.Command
import app.tauri.annotation.InvokeArg
import app.tauri.annotation.Permission
import app.tauri.annotation.TauriPlugin
import app.tauri.plugin.Invoke
import app.tauri.plugin.JSObject
import app.tauri.plugin.Plugin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

// Args. Required = lateinit, optional = nullable, default = assigned value.
// Field names MUST match the camelCase the Rust side serializes.
@InvokeArg
internal class OpenCameraArgs {
    var quality: Int = 80
    var allowEdit: Boolean = false
    var note: String? = null
}

@TauriPlugin(
    permissions = [
        // Each `alias` becomes a key in the JSON object that
        // checkPermissions / requestPermissions returns to JS.
        Permission(strings = [Manifest.permission.CAMERA], alias = "camera"),
        Permission(strings = [Manifest.permission.POST_NOTIFICATIONS], alias = "postNotification"),
    ]
)
class MyPlugin(private val activity: Activity) : Plugin(activity) {

    // Long-running work goes on this scope, NOT the main thread.
    private val ioScope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    override fun load(webView: WebView) {
        // Called once per webview attach. Initialize singletons here.
    }

    @Command
    fun ping(invoke: Invoke) {
        val out = JSObject()
        out.put("pong", true)
        invoke.resolve(out)
    }

    @Command
    fun openCamera(invoke: Invoke) {
        val args = invoke.parseArgs(OpenCameraArgs::class.java)
        // ... pretend we launched a camera Intent and got a result back ...
        val out = JSObject()
        out.put("path", "/storage/emulated/0/DCIM/photo-${args.quality}.jpg")
        invoke.resolve(out)
    }

    @Command
    fun readBigFile(invoke: Invoke) {
        // IMPORTANT: do not block here. Hand off to IO dispatcher and resolve
        // when work completes. Blocking the main thread risks an ANR dialog.
        ioScope.launch {
            val bytes = readFromDisk()
            val out = JSObject()
            out.put("byteLength", bytes.size)
            invoke.resolve(out)
        }
    }

    private fun readFromDisk(): ByteArray {
        // ... actual IO ...
        return ByteArray(0)
    }
}
