// ios/Sources/MyPlugin/MyPlugin.swift
//
// Generated by `tauri plugin ios add` and then edited to add commands.
// Every command must be marked @objc and take a single Invoke argument —
// Tauri discovers them via the Objective-C runtime. Drop @objc and the
// command silently fails to register at runtime.

import AVFoundation
import SwiftRs
import Tauri
import UserNotifications
import WebKit

// Arg structs are plain Decodable. Optional = `Type?`. Defaults are NOT
// supported here — use Type? and default at the call site if needed.
class OpenCameraArgs: Decodable {
    let quality: Int
    var allowEdit: Bool?
    var note: String?
}

class MyPlugin: Plugin {

    @objc public override func load(webview: WKWebView) {
        // Called once per webview attach. Initialize singletons here.
    }

    @objc public func ping(_ invoke: Invoke) {
        invoke.resolve(["pong": true])
    }

    @objc public func openCamera(_ invoke: Invoke) throws {
        let args = try invoke.parseArgs(OpenCameraArgs.self)
        // ... pretend we launched UIImagePickerController and got a result ...
        invoke.resolve([
            "path": "/var/mobile/Containers/Data/Application/.../photo-\(args.quality).jpg"
        ])
    }

    // ----------------------------------------------------------------------
    // Permission UX. On iOS you override these manually (unlike Android,
    // where the @TauriPlugin annotation drives them). Resolve with values
    // from the PermissionState set: granted | denied | prompt | prompt-with-rationale.
    // ----------------------------------------------------------------------

    @objc public override func checkPermissions(_ invoke: Invoke) {
        let camera: String
        switch AVCaptureDevice.authorizationStatus(for: .video) {
        case .authorized: camera = "granted"
        case .denied, .restricted: camera = "denied"
        case .notDetermined: camera = "prompt"
        @unknown default: camera = "prompt"
        }
        invoke.resolve(["camera": camera])
    }

    @objc public override func requestPermissions(_ invoke: Invoke) {
        AVCaptureDevice.requestAccess(for: .video) { granted in
            invoke.resolve(["camera": granted ? "granted" : "denied"])
        }
    }
}

// Tauri's Swift bridge expects this factory function. The plugin name string
// passed to the Rust Builder::new("...") MUST match the lowercased base name
// here, otherwise run_mobile_plugin("...") errors with "plugin not loaded".
@_cdecl("init_plugin_my_plugin")
func initPlugin() -> Plugin {
    return MyPlugin()
}
